services:
  cdr-bank-mysql:
    image: mysql:8.0.36
    container_name: cdr-bank-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: bankuser
      MYSQL_PASSWORD: bankpass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    # Пробрасываем порт 3306 контейнера на хост (все интерфейсы)
    ports:
      - "3306:3306"

volumes:
  mysql-data:
    driver: local
