version: '3.1'

services:
  cdr-bank-banking-api:
    # вместо image из registry
    image: cdr-bank-banking-api:local
    container_name: cdr-bank-local-banking-api

    # указываем, что нужно сделать локальную сборку
    build:
      context: ../../../
      dockerfile: ./CDR-Bank.Banking/Dockerfile

    # Если хотите — можете тут же подменить env на «development»
    environment:
      APPLICATION_ENVIRONMENT: local
      ASPNETCORE_ENVIRONMENT: Development
      # IP из локальной сети, например
      CONTAINER_IP: 172.35.0.10
      AUTHORIZATION_ENDPOINT: http://localhost:5000
      BANKING_DB_CONNECTION_STRING: "Server=cdr-bank-db;Database=BankingDb;User Id=root;Password=pass;"

    # Для простоты монтируем логи в папку на хосте
    volumes:
      - ./logs:/app/logs
