services:
  cdr-bank:
    container_name: cdr-bank-banking
    build:
      context: ./../
      dockerfile: CDR-Bank.Banking/Dockerfile
    environment:
      - ConnectionStrings__IdentityDb=Server=cdr-db;Port=3306;Database=IdentityDb;User=root;Password=rootpassword;SslMode=Preferred;
      - ApiSettings__SecretKey="meGeNdIcklaryBErSKineYKNoWLiNEuSnESCoNAreCIonsABLe"
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      cdr_bank_network:
        ipv4_address: ${CONTAINER_IP}
        aliases:
          - banking-api